services:
  backend:
    build: ./backend
    ports:
      - "3001:3001" 
    networks:
      - mern_network

  frontend:
    build: ./client
    ports:
      - "3000:3000"  
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge 

